import type { OperationalJourney } from '../types.js';

/** Correct operational order for front desk — screens must not skip steps. */
export const frontDeskSpine: OperationalJourney = {
  id: 'front_desk_spine',
  label: 'Front desk (OPD / walk-in)',
  description: 'Registration → eligibility → appointment/walk-in → check-in → token → handoff to clinical queue.',
  steps: [
    {
      id: 'register',
      label: 'Register / find patient',
      lifecycleId: 'patient_identity',
      targetState: 'registered',
      route: '/reception/registration',
      roles: ['receptionist'],
    },
    {
      id: 'preauth',
      label: 'Insurance / corporate verification',
      lifecycleId: 'insurance_preauth',
      targetState: 'approved',
      route: '/reception/billing',
      roles: ['receptionist', 'billing'],
      dependsOn: ['register'],
    },
    {
      id: 'schedule',
      label: 'Appointment or walk-in slot',
      lifecycleId: 'opd_visit',
      targetState: 'appointment_or_walkin',
      route: '/reception/appointments',
      roles: ['receptionist', 'scheduler'],
      dependsOn: ['register'],
    },
    {
      id: 'checkin',
      label: 'Check-in',
      lifecycleId: 'opd_visit',
      targetState: 'checked_in',
      route: '/reception/checkin',
      roles: ['receptionist'],
      dependsOn: ['schedule'],
    },
    {
      id: 'routing',
      label: 'Department routing',
      lifecycleId: 'opd_visit',
      targetState: 'routed',
      route: '/reception/queue',
      roles: ['receptionist', 'nurse'],
      dependsOn: ['checkin'],
    },
    {
      id: 'queue',
      label: 'Token & queue',
      lifecycleId: 'opd_visit',
      targetState: 'queued',
      route: '/reception/queue',
      roles: ['receptionist'],
      dependsOn: ['routing'],
    },
    {
      id: 'billing_exit',
      label: 'OPD billing (exit)',
      lifecycleId: 'billing_invoice',
      targetState: 'paid',
      route: '/reception/billing',
      roles: ['receptionist', 'billing'],
      dependsOn: ['queue'],
    },
  ],
};

export const clinicalOpdSpine: OperationalJourney = {
  id: 'clinical_opd_spine',
  label: 'Clinical OPD',
  description: 'Queue → consultation → orders → results review → close encounter.',
  steps: [
    {
      id: 'queue',
      label: 'OPD queue',
      lifecycleId: 'opd_visit',
      targetState: 'queued',
      route: '/doctor/queue',
      roles: ['doctor'],
    },
    {
      id: 'consult',
      label: 'Consultation',
      lifecycleId: 'clinical_consultation',
      targetState: 'in_consultation',
      route: '/doctor/patients',
      roles: ['doctor'],
      dependsOn: ['queue'],
    },
    {
      id: 'orders',
      label: 'Orders (lab / Rx / radiology)',
      lifecycleId: 'visit_encounter',
      targetState: 'orders_pending',
      roles: ['doctor'],
      dependsOn: ['consult'],
    },
    {
      id: 'billing',
      label: 'Billing & payment',
      lifecycleId: 'opd_visit',
      targetState: 'billing_pending',
      route: '/reception/billing',
      roles: ['receptionist', 'billing'],
      dependsOn: ['orders'],
    },
    {
      id: 'close',
      label: 'Close visit',
      lifecycleId: 'opd_visit',
      targetState: 'completed',
      roles: ['doctor', 'receptionist', 'billing'],
      dependsOn: ['billing'],
    },
    {
      id: 'followup',
      label: 'Follow-up',
      lifecycleId: 'opd_visit',
      targetState: 'follow_up_scheduled',
      route: '/reception/appointments',
      roles: ['doctor', 'receptionist'],
      dependsOn: ['close'],
    },
  ],
};

export const ipdSpine: OperationalJourney = {
  id: 'ipd_spine',
  label: 'Inpatient (IPD)',
  description: 'Admission request → bed → nursing care → clinical rounds → ancillary → discharge.',
  steps: [
    {
      id: 'admit_request',
      label: 'Admission & bed',
      lifecycleId: 'admission',
      targetState: 'admitted',
      route: '/reception/ipd',
      roles: ['receptionist', 'nurse'],
    },
    {
      id: 'nursing',
      label: 'Ward care & vitals',
      lifecycleId: 'nursing_round',
      targetState: 'active_care',
      route: '/nurse/ward',
      roles: ['nurse'],
      dependsOn: ['admit_request'],
    },
    {
      id: 'doctor_rounds',
      label: 'Doctor rounds & notes',
      lifecycleId: 'inpatient_care',
      targetState: 'active_care',
      route: '/doctor/ipd',
      roles: ['doctor'],
      dependsOn: ['admit_request'],
    },
    {
      id: 'discharge_ready',
      label: 'Discharge planning',
      lifecycleId: 'discharge',
      targetState: 'discharge_ready',
      route: '/nurse/discharge',
      roles: ['doctor', 'nurse'],
      dependsOn: ['nursing', 'doctor_rounds'],
    },
    {
      id: 'final_bill',
      label: 'Final bill & discharge',
      lifecycleId: 'billing_invoice',
      targetState: 'paid',
      route: '/billing-dept/ipd-billing',
      roles: ['billing', 'receptionist'],
      dependsOn: ['discharge_ready'],
    },
  ],
};

export const emergencySpine: OperationalJourney = {
  id: 'emergency_spine',
  label: 'Emergency',
  description: 'Rapid registration → triage → treatment → IPD transfer or ED discharge.',
  steps: [
    {
      id: 'ed_register',
      label: 'Emergency registration',
      lifecycleId: 'emergency_case',
      targetState: 'triage_pending',
      route: '/emergency/triage',
      roles: ['receptionist', 'emergency'],
    },
    {
      id: 'triage',
      label: 'Triage',
      lifecycleId: 'emergency_case',
      targetState: 'triaged',
      route: '/emergency/triage',
      roles: ['nurse', 'emergency'],
      dependsOn: ['ed_register'],
    },
    {
      id: 'treat',
      label: 'Treatment',
      lifecycleId: 'emergency_case',
      targetState: 'treatment',
      route: '/emergency/treatment',
      roles: ['doctor', 'emergency'],
      dependsOn: ['triage'],
    },
    {
      id: 'disposition',
      label: 'Disposition (IPD / discharge / refer)',
      lifecycleId: 'emergency_case',
      targetState: 'discharged',
      route: '/emergency/cases',
      roles: ['doctor'],
      dependsOn: ['treat'],
    },
  ],
};

export const OPERATIONAL_JOURNEYS = [
  frontDeskSpine,
  clinicalOpdSpine,
  ipdSpine,
  emergencySpine,
] as const;
