import { UserRole } from "@/types/roles";

export interface RoleTab {
  key: string;
  label: string;
  path: string;
}

export const ROLE_TABS: Record<UserRole, RoleTab[]> = {
  admin: [
    { key: "dashboard", label: "Dashboard", path: "/admin" },
    {
      key: "morning-briefing",
      label: "AI Briefing",
      path: "/admin/morning-briefing",
    },
    {
      key: "command-center",
      label: "Command Center",
      path: "/admin/command-center",
    },
    {
      key: "mortality",
      label: "Mortality Analytics",
      path: "/admin/mortality",
    },
    { key: "ai-workflow", label: "AI Workflow", path: "/admin/ai-workflow" },
    {
      key: "disease-mapping",
      label: "Disease Mapping",
      path: "/admin/disease-mapping",
    },
    {
      key: "geo-intelligence",
      label: "Geo Intelligence",
      path: "/admin/geo-intelligence",
    },
    { key: "data-mining", label: "Data Mining", path: "/admin/data-mining" },
    { key: "kaizen", label: "Kaizen", path: "/admin/kaizen" },
    {
      key: "revenue-cycle",
      label: "Revenue Cycle",
      path: "/admin/revenue-cycle",
    },
    {
      key: "finance-hub",
      label: "Finance & Expenses",
      path: "/admin/finance-hub",
    },
    {
      key: "treatment-success",
      label: "Treatment Outcomes",
      path: "/admin/treatment-success",
    },
    { key: "hr-staff", label: "Staff", path: "/hr/staff" },
    { key: "hr-scheduling", label: "Scheduling", path: "/hr/scheduling" },
    { key: "hr-leave", label: "Leave", path: "/hr/leave" },
    { key: "staff", label: "Staff (Legacy)", path: "/admin/staff" },
    { key: "departments", label: "Departments", path: "/admin/departments" },
    { key: "finance", label: "Finance", path: "/admin/finance" },
    { key: "expenses", label: "Expenses", path: "/admin/expenses" },
    { key: "approvals", label: "Approvals", path: "/admin/approvals" },
    { key: "claims", label: "Claims", path: "/admin/claims" },
    {
      key: "doctor-sharing",
      label: "Doctor Sharing",
      path: "/admin/doctor-sharing",
    },
    { key: "mrd", label: "MRD", path: "/admin/mrd" },
    { key: "mis", label: "MIS Reports", path: "/admin/mis" },
    { key: "audit", label: "Audit", path: "/admin/audit" },
    { key: "phonebook", label: "Phone Book", path: "/admin/phonebook" },
    { key: "crm", label: "CRM", path: "/admin/crm" },
    { key: "settings", label: "Settings", path: "/admin/settings" },
  ],
  doctor: [
    { key: "dashboard", label: "Dashboard", path: "/doctor" },
    { key: "patients", label: "Patients", path: "/doctor/patients" },
    { key: "queue", label: "OPD Queue", path: "/doctor/queue" },
    { key: "schedule", label: "Schedule", path: "/doctor/schedule" },
    { key: "labs", label: "Labs", path: "/doctor/labs" },
    { key: "radiology", label: "Radiology", path: "/doctor/radiology" },
    { key: "ipd", label: "IPD", path: "/doctor/ipd" },
    { key: "analytics", label: "Analytics", path: "/doctor/analytics" },
  ],
  jr_doctor: [
    { key: "dashboard", label: "Dashboard", path: "/jr-doctor" },
    { key: "queue", label: "OPD Queue", path: "/jr-doctor/queue" },
    { key: "patients", label: "Patients", path: "/jr-doctor/patients" },
  ],
  nurse: [
    { key: "dashboard", label: "Dashboard", path: "/nurse" },
    { key: "shift", label: "Shift Handoff", path: "/nurse/shift" },
    { key: "task-board", label: "Task Board", path: "/nurse/task-board" },
    { key: "ward", label: "My Ward", path: "/nurse/ward" },
    { key: "admissions", label: "Admissions", path: "/nurse/admissions" },
    { key: "tasks", label: "Tasks", path: "/nurse/tasks" },
    { key: "orders", label: "Order Verify", path: "/nurse/orders" },
    { key: "medications", label: "Medications", path: "/nurse/medications" },
    { key: "vitals", label: "Vitals", path: "/nurse/vitals" },
    { key: "assessments", label: "Assessments", path: "/nurse/assessments" },
    { key: "care-plan", label: "Care Plan", path: "/nurse/care-plan" },
    { key: "io", label: "Intake/Output", path: "/nurse/io" },
    { key: "discharge", label: "Discharge", path: "/nurse/discharge" },
    { key: "reports", label: "Reports", path: "/nurse/reports" },
  ],
  receptionist: [
    { key: "dashboard", label: "Dashboard", path: "/reception" },
    {
      key: "registration",
      label: "Registration",
      path: "/reception/registration",
    },
    {
      key: "appointments",
      label: "Appointments",
      path: "/reception/appointments",
    },
    { key: "checkin", label: "Check-In", path: "/reception/checkin" },
    { key: "queue", label: "Queue", path: "/reception/queue" },
    { key: "billing", label: "Billing", path: "/reception/billing" },
    { key: "beds", label: "Beds", path: "/reception/beds" },
    { key: "ipd", label: "IPD", path: "/reception/ipd" },
    { key: "visitors", label: "Visitors", path: "/reception/visitors" },
    { key: "handover", label: "Handover", path: "/reception/handover" },
    { key: "enquiries", label: "Enquiries", path: "/reception/enquiries" },
    { key: "branches", label: "Branches", path: "/reception/branches" },
    { key: "feedback", label: "Feedback", path: "/reception/feedback" },
  ],
  lab_technician: [
    { key: "dashboard", label: "Dashboard", path: "/lab" },
    { key: "orders", label: "Orders", path: "/lab/orders" },
    { key: "phlebotomy", label: "Phlebotomy", path: "/lab/phlebotomy" },
    { key: "accession", label: "Accession", path: "/lab/accession" },
    { key: "worklist", label: "Worklist", path: "/lab/worklist" },
    { key: "sections", label: "Sections", path: "/lab/sections" },
    { key: "samples", label: "Samples", path: "/lab/samples" },
    { key: "entry", label: "Test Entry", path: "/lab/entry" },
    { key: "verification", label: "Verification", path: "/lab/verification" },
    { key: "critical", label: "Critical", path: "/lab/critical" },
    { key: "amendments", label: "Amendments", path: "/lab/amendments" },
    { key: "reports", label: "Reports", path: "/lab/reports" },
    { key: "audit", label: "Audit", path: "/lab/audit" },
    { key: "tat", label: "TAT / SLA", path: "/lab/tat" },
    { key: "billing-handoff", label: "Billing", path: "/lab/billing-handoff" },
    { key: "storage", label: "Storage", path: "/lab/storage" },
    { key: "catalog", label: "Catalog", path: "/lab/catalog" },
    { key: "qc", label: "QC", path: "/lab/qc" },
    { key: "analyzers", label: "Machine Integration", path: "/lab/analyzers" },
    { key: "blood-bank", label: "Blood Bank", path: "/blood-bank" },
    { key: "blood-donors", label: "BB Donors", path: "/blood-bank/donors" },
    { key: "blood-inventory", label: "BB Inventory", path: "/blood-bank/inventory" },
    { key: "blood-issue", label: "BB Issue", path: "/blood-bank/issue" },
    { key: "blood-compliance", label: "BB Compliance", path: "/blood-bank/compliance" },
    { key: "referral", label: "Referral", path: "/lab/referral" },
    { key: "consumables", label: "Consumables", path: "/lab/consumables" },
    { key: "histo", label: "Histopathology", path: "/lab/histo" },
  ],
  pharmacist: [
    { key: "dashboard", label: "Dashboard", path: "/pharmacy" },
    {
      key: "prescriptions",
      label: "Prescriptions",
      path: "/pharmacy/prescriptions",
    },
    { key: "inventory", label: "Inventory", path: "/pharmacy/inventory" },
    { key: "drugs", label: "Drugs", path: "/pharmacy/drugs" },
    { key: "reports", label: "Reports", path: "/pharmacy/reports" },
    { key: "billing", label: "Billing", path: "/pharmacy/billing" },
    { key: "suppliers", label: "Suppliers", path: "/pharmacy/suppliers" },
    { key: "purchase", label: "Purchase Orders", path: "/pharmacy/purchase" },
    { key: "schedule-h", label: "Schedule H", path: "/pharmacy/schedule-h" },
    { key: "queries", label: "Queries", path: "/pharmacy/queries" },
    { key: "formulary", label: "Formulary", path: "/pharmacy/formulary" },
    { key: "indent", label: "Ward Indent", path: "/pharmacy/indent" },
    { key: "returns", label: "Returns", path: "/pharmacy/returns" },
    { key: "narcotics", label: "Narcotics", path: "/pharmacy/narcotics" },
    { key: "expiry", label: "Expiry", path: "/pharmacy/expiry" },
    { key: "audit", label: "Audit", path: "/pharmacy/audit" },
    { key: "barcode", label: "Barcode", path: "/pharmacy/barcode" },
    { key: "counseling", label: "Counseling", path: "/pharmacy/counseling" },
    { key: "refills", label: "Refills", path: "/pharmacy/refills" },
    { key: "compounding", label: "Compounding", path: "/pharmacy/compounding" },
    { key: "cold-chain", label: "Cold Chain", path: "/pharmacy/cold-chain" },
    { key: "interactions", label: "Interactions", path: "/pharmacy/interactions" },
  ],
  billing: [
    { key: "dashboard", label: "Dashboard", path: "/billing-dept" },
    { key: "invoices", label: "Invoices", path: "/billing-dept/invoices" },
    { key: "payments", label: "Payments", path: "/billing-dept/payments" },
    {
      key: "ipd-billing",
      label: "IPD Billing",
      path: "/billing-dept/ipd-billing",
    },
    { key: "packages", label: "Packages", path: "/billing-dept/packages" },
    { key: "counselling", label: "Counselling", path: "/billing-dept/counselling" },
    {
      key: "health-plans",
      label: "Health Plans",
      path: "/billing-dept/health-plans",
    },
    { key: "revenue", label: "Revenue", path: "/billing-dept/revenue" },
    { key: "insurance", label: "Insurance", path: "/billing-dept/insurance" },
    { key: "pre-auth", label: "Pre-auth", path: "/billing-dept/pre-auth" },
    {
      key: "tpa-charges",
      label: "TPA Charges",
      path: "/billing-dept/tpa-charges",
    },
    {
      key: "reconciliation",
      label: "Reconciliation",
      path: "/billing-dept/reconciliation",
    },
    { key: "gst", label: "GST Reports", path: "/billing-dept/gst" },
    { key: "finance", label: "Finance", path: "/billing-dept/finance" },
    { key: "reports", label: "Reports", path: "/billing-dept/reports" },
    {
      key: "charge-master",
      label: "Charge Master",
      path: "/billing-dept/charge-master",
    },
    { key: "tpa-desk", label: "TPA Desk", path: "/billing-dept/tpa-desk" },
    { key: "copay", label: "Co-Pay", path: "/billing-dept/copay" },
    { key: "ecl", label: "ECL Letters", path: "/billing-dept/ecl" },
    { key: "claims", label: "Claims", path: "/billing-dept/claims" },
    { key: "denials", label: "Denials", path: "/billing-dept/denials" },
    {
      key: "pharmacy-billing",
      label: "Pharmacy Billing",
      path: "/billing-dept/pharmacy-billing",
    },
    {
      key: "corporate-billing",
      label: "Corporate Billing",
      path: "/billing-dept/corporate-billing",
    },
    { key: "cashier", label: "Cashier", path: "/billing-dept/cashier" },
    {
      key: "copay-audit",
      label: "Copay Audit",
      path: "/billing-dept/copay-audit",
    },
    {
      key: "scheme-billing",
      label: "Scheme Billing",
      path: "/billing-dept/scheme-billing",
    },
    {
      key: "settlement",
      label: "Settlement",
      path: "/billing-dept/settlement",
    },
  ],
  radiologist: [
    { key: "dashboard", label: "Dashboard", path: "/radiology" },
    { key: "orders", label: "Orders", path: "/radiology/orders" },
    { key: "worklist", label: "Worklist", path: "/radiology/worklist" },
    { key: "reports", label: "Reports", path: "/radiology/reports" },
    { key: "critical", label: "Critical Callback", path: "/radiology/critical" },
    { key: "templates", label: "Templates", path: "/radiology/templates" },
    { key: "schedule", label: "Schedule", path: "/radiology/schedule" },
    { key: "contrast", label: "Contrast Log", path: "/radiology/contrast" },
    { key: "tat", label: "TAT / SLA", path: "/radiology/tat" },
    { key: "amendments", label: "Amendments", path: "/radiology/amendments" },
    { key: "peer-review", label: "Peer Review", path: "/radiology/peer-review" },
    { key: "dose", label: "Dose Registry", path: "/radiology/dose" },
    { key: "telerad", label: "Teleradiology", path: "/radiology/telerad" },
    { key: "pacs", label: "PACS Config", path: "/radiology/pacs" },
    { key: "modality-worklist", label: "Modality Worklist", path: "/radiology/modality-worklist" },
    { key: "settings", label: "Settings", path: "/radiology/settings" },
  ],
  ot_coordinator: [
    { key: "dashboard", label: "Dashboard", path: "/ot" },
    { key: "board", label: "Today board", path: "/ot/board" },
    { key: "schedule", label: "Schedule", path: "/ot/schedule" },
    { key: "rooms", label: "OT Rooms", path: "/ot/rooms" },
    { key: "teams", label: "Teams", path: "/ot/teams" },
    { key: "preop", label: "Pre-Op", path: "/ot/preop" },
    { key: "intraop", label: "Intraoperative", path: "/ot/intraop" },
    { key: "postop", label: "Post-Op", path: "/ot/postop" },
    { key: "inventory", label: "Inventory", path: "/ot/inventory" },
    { key: "reports", label: "Reports", path: "/ot/reports" },
    { key: "analytics", label: "Analytics", path: "/ot/analytics" },
  ],
  inventory_manager: [
    { key: "dashboard", label: "Dashboard", path: "/inventory" },
    { key: "issue", label: "Stock issue", path: "/inventory/issue" },
    { key: "grn", label: "GRN receive", path: "/inventory/grn" },
    { key: "catalog", label: "Catalog", path: "/inventory/catalog" },
    {
      key: "stock-entry",
      label: "Stock Entry",
      path: "/inventory/stock-entry",
    },
    {
      key: "distribution",
      label: "Distribution",
      path: "/inventory/distribution",
    },
    {
      key: "requisitions",
      label: "Requisitions",
      path: "/inventory/requisitions",
    },
    {
      key: "procurement",
      label: "Procurement",
      path: "/inventory/procurement",
    },
    {
      key: "adjustments",
      label: "Adjustments",
      path: "/inventory/adjustments",
    },
    { key: "equipment", label: "Equipment", path: "/inventory/equipment" },
    { key: "reports", label: "Reports", path: "/inventory/reports" },
  ],
  emergency: [
    { key: "dashboard", label: "Dashboard", path: "/emergency" },
    { key: "triage", label: "Triage", path: "/emergency/triage" },
    { key: "cases", label: "Cases", path: "/emergency/cases" },
    { key: "treatment", label: "Treatment", path: "/emergency/treatment" },
    { key: "orders", label: "Orders", path: "/emergency/orders" },
    {
      key: "observation",
      label: "Observation",
      path: "/emergency/observation",
    },
    { key: "mlc", label: "MLC", path: "/emergency/mlc" },
    { key: "ambulance", label: "Ambulance", path: "/emergency/ambulance" },
    { key: "reports", label: "Reports", path: "/emergency/reports" },
  ],
  hr_manager: [
    { key: "dashboard", label: "Dashboard", path: "/hr" },
    { key: "staff", label: "Staff Profiles", path: "/hr/staff" },
    { key: "scheduling", label: "Scheduling", path: "/hr/scheduling" },
    { key: "attendance", label: "Attendance", path: "/hr/attendance" },
    { key: "leave", label: "Leave", path: "/hr/leave" },
    { key: "credentials", label: "Credentials", path: "/hr/credentials" },
    { key: "training", label: "Training", path: "/hr/training" },
    { key: "performance", label: "Performance", path: "/hr/performance" },
    { key: "reports", label: "Reports", path: "/hr/reports" },
  ],
  scheduler: [
    { key: "dashboard", label: "Dashboard", path: "/scheduling" },
    { key: "book", label: "Book", path: "/scheduling/book" },
    { key: "calendar", label: "Calendar", path: "/scheduling/calendar" },
    { key: "doctors", label: "Doctors", path: "/scheduling/doctors" },
    { key: "resources", label: "Resources", path: "/scheduling/resources" },
    { key: "waitlist", label: "Waitlist", path: "/scheduling/waitlist" },
    {
      key: "teleconsult",
      label: "Teleconsult",
      path: "/scheduling/teleconsult",
    },
    { key: "reports", label: "Reports", path: "/scheduling/reports" },
  ],
  dialysis_tech: [
    { key: "dashboard", label: "Dashboard", path: "/dialysis" },
    { key: "patients", label: "Patients", path: "/dialysis/patients" },
    { key: "schedule", label: "Schedule", path: "/dialysis/schedule" },
    {
      key: "session",
      label: "Session / Flow Chart",
      path: "/dialysis/session",
    },
    { key: "machines", label: "Machines", path: "/dialysis/machines" },
    { key: "consumables", label: "Consumables", path: "/dialysis/consumables" },
    { key: "billing", label: "Billing & Packages", path: "/dialysis/billing" },
    { key: "reports", label: "Reports", path: "/dialysis/reports" },
  ],
  crm_manager: [
    { key: "dashboard", label: "Dashboard", path: "/crm" },
    { key: "leads", label: "Lead Pipeline", path: "/crm/leads" },
    { key: "follow-ups", label: "Follow-ups", path: "/crm/follow-ups" },
    { key: "counsellors", label: "Counsellor", path: "/crm/counsellors" },
    { key: "packages", label: "Packages", path: "/crm/packages" },
    { key: "referrals", label: "Referrals", path: "/crm/referrals" },
    { key: "lifecycle", label: "Patient Lifecycle", path: "/crm/lifecycle" },
    { key: "campaigns", label: "Care Journeys", path: "/crm/campaigns" },
    {
      key: "drip-campaigns",
      label: "Drip Campaigns",
      path: "/crm/drip-campaigns",
    },
    { key: "whatsapp", label: "WhatsApp Auto", path: "/crm/whatsapp" },
    { key: "navayu", label: "Navayu MSK", path: "/crm/navayu" },
    { key: "experience", label: "Patient Experience", path: "/crm/experience" },
    { key: "reports", label: "Analytics", path: "/crm/reports" },
  ],
};

export const ROLE_BASE_PATH: Record<UserRole, string> = {
  admin: "/admin",
  doctor: "/doctor",
  jr_doctor: "/jr-doctor",
  nurse: "/nurse",
  receptionist: "/reception",
  lab_technician: "/lab",
  pharmacist: "/pharmacy",
  billing: "/billing-dept",
  radiologist: "/radiology",
  ot_coordinator: "/ot",
  inventory_manager: "/inventory",
  emergency: "/emergency",
  hr_manager: "/hr",
  scheduler: "/scheduling",
  dialysis_tech: "/dialysis",
  crm_manager: "/crm",
};

