/**
 * Canonical Adrine platform event names for Hospital OS.
 * Must match domain-api / kernel outbox naming: adrine.<domain>.<entity>.<verb>
 */
export const HospitalPlatformEvents = {
  patient: {
    registered: 'adrine.patient.profile.created',
    updated: 'adrine.patient.profile.updated',
    merged: 'adrine.patient.identity.merged',
  },
  appointment: {
    booked: 'adrine.appointment.booked',
    checkedIn: 'adrine.appointment.checked_in',
    cancelled: 'adrine.appointment.cancelled',
    noShow: 'adrine.appointment.no_show',
  },
  queue: {
    tokenIssued: 'adrine.queue.token.issued',
    called: 'adrine.queue.patient.called',
    completed: 'adrine.queue.visit.completed',
  },
  encounter: {
    opened: 'adrine.encounter.opened',
    closed: 'adrine.encounter.closed',
  },
  emergency: {
    registered: 'adrine.emergency.case.registered',
    triaged: 'adrine.emergency.case.triaged',
    admitted: 'adrine.emergency.case.admitted_to_ipd',
    discharged: 'adrine.emergency.case.discharged',
  },
  admission: {
    requested: 'adrine.admission.requested',
    admitted: 'adrine.admission.confirmed',
    transferred: 'adrine.admission.transferred',
    dischargeReady: 'adrine.admission.discharge_ready',
    discharged: 'adrine.admission.discharged',
  },
  ipd: {
    admissionRequested: 'adrine.ipd.admission.requested',
    admissionApproved: 'adrine.ipd.admission.approved',
    admitted: 'adrine.ipd.admission.confirmed',
    activeCareStarted: 'adrine.ipd.care.started',
    transferInitiated: 'adrine.ipd.transfer.initiated',
    transferred: 'adrine.ipd.transfer.completed',
    dischargeInitiated: 'adrine.ipd.discharge.initiated',
    discharged: 'adrine.ipd.discharge.completed',
    admissionCancelled: 'adrine.ipd.admission.cancelled',
  },
  bed: {
    allocated: 'adrine.bed.allocated',
    reserved: 'adrine.bed.reserved',
    occupied: 'adrine.bed.occupied',
    released: 'adrine.bed.released',
    available: 'adrine.bed.available',
    maintenanceStarted: 'adrine.bed.maintenance.started',
    blocked: 'adrine.bed.blocked',
  },
  nursing: {
    taskAcknowledged: 'adrine.nursing.task.acknowledged',
    taskStarted: 'adrine.nursing.task.started',
    taskCompleted: 'adrine.nursing.task.completed',
    taskEscalated: 'adrine.nursing.task.escalated',
    taskMissed: 'adrine.nursing.task.missed',
  },
  mar: {
    scheduleCreated: 'adrine.mar.schedule.created',
    administered: 'adrine.mar.medication.administered',
    held: 'adrine.mar.medication.held',
    missed: 'adrine.mar.medication.missed',
    refused: 'adrine.mar.medication.refused',
  },
  clinical: {
    vitalsRecorded: 'adrine.clinical.vitals.recorded',
    noteSigned: 'adrine.emr.note.signed',
    prescriptionIssued: 'adrine.clinical.prescription.issued',
  },
  lab: {
    ordered: 'adrine.lab.order.created',
    sampleCollected: 'adrine.lab.sample.collected',
    sampleTransferred: 'adrine.lab.sample.transferred',
    processingStarted: 'adrine.lab.processing.started',
    resultEntered: 'adrine.lab.result.entered',
    resultCritical: 'adrine.lab.result.critical',
    reportApproved: 'adrine.lab.report.approved',
    reportPublished: 'adrine.lab.report.published',
    orderCompleted: 'adrine.lab.order.completed',
    orderCancelled: 'adrine.lab.order.cancelled',
    recollectRequired: 'adrine.lab.recollect.required',
    resultVerified: 'adrine.lab.result.verified',
    reportReleased: 'adrine.lab.report.released',
  },
  radiology: {
    ordered: 'adrine.radiology.order.created',
    imagingStarted: 'adrine.radiology.imaging.started',
    imagesAcquired: 'adrine.radiology.images.acquired',
    criticalFlagged: 'adrine.radiology.critical.flagged',
    reportApproved: 'adrine.radiology.report.approved',
    reportPublished: 'adrine.radiology.report.published',
    orderCompleted: 'adrine.radiology.order.completed',
    orderCancelled: 'adrine.radiology.order.cancelled',
    reported: 'adrine.radiology.report.finalized',
  },
  ot: {
    caseScheduled: 'adrine.ot.case.scheduled',
    caseConfirmed: 'adrine.ot.case.confirmed',
    preopCompleted: 'adrine.ot.preop.completed',
    surgeryStarted: 'adrine.ot.surgery.started',
    surgeryCompleted: 'adrine.ot.surgery.completed',
    caseCompleted: 'adrine.ot.case.completed',
    caseCancelled: 'adrine.ot.case.cancelled',
  },
  inventory: {
    itemCreated: 'adrine.inventory.item.created',
    moveSubmitted: 'adrine.inventory.move.submitted',
    moveApproved: 'adrine.inventory.move.approved',
    stockIssued: 'adrine.inventory.stock.issued',
    stockReceived: 'adrine.inventory.stock.received',
    moveCancelled: 'adrine.inventory.move.cancelled',
  },
  dialysis: {
    sessionScheduled: 'adrine.dialysis.session.scheduled',
    patientCheckedIn: 'adrine.dialysis.patient.checked_in',
    sessionStarted: 'adrine.dialysis.session.started',
    sessionCompleted: 'adrine.dialysis.session.completed',
    sessionCancelled: 'adrine.dialysis.session.cancelled',
  },
  pharmacy: {
    prescriptionCreated: 'adrine.pharmacy.prescription.created',
    inventoryReserved: 'adrine.pharmacy.inventory.reserved',
    dispensePreparing: 'adrine.pharmacy.dispense.preparing',
    dispenseCompleted: 'adrine.pharmacy.dispense.completed',
    dispensePartial: 'adrine.pharmacy.dispense.partial',
    returnProcessed: 'adrine.pharmacy.return.processed',
    inventoryReleased: 'adrine.pharmacy.inventory.released',
    prescriptionCancelled: 'adrine.pharmacy.prescription.cancelled',
    dispensed: 'adrine.pharmacy.dispense.completed',
    stockLow: 'adrine.pharmacy.stock.low',
  },
  billing: {
    estimateCreated: 'adrine.billing.estimate.created',
    draftOpened: 'adrine.billing.invoice.draft_opened',
    invoiceGenerated: 'adrine.billing.invoice.generated',
    paymentCollected: 'adrine.billing.payment.collected',
    paymentReceived: 'adrine.billing.payment.received',
    invoiceSettled: 'adrine.billing.invoice.settled',
    receiptGenerated: 'adrine.billing.receipt.generated',
    invoiceVoided: 'adrine.billing.invoice.voided',
    invoiceRecalculated: 'adrine.billing.invoice.recalculated',
    chargeAdded: 'adrine.billing.charge.added',
    chargeUpdated: 'adrine.billing.charge.updated',
    chargeReversed: 'adrine.billing.charge.reversed',
    refundIssued: 'adrine.billing.refund.issued',
  },
  opd: {
    visitCompleted: 'adrine.opd.visit.completed',
  },
  insurance: {
    preauthRequested: 'adrine.insurance.preauth.requested',
    preauthApproved: 'adrine.insurance.preauth.approved',
    claimSubmitted: 'adrine.insurance.claim.submitted',
    authorizationInitiated: 'adrine.insurance.authorization.initiated',
    submitted: 'adrine.insurance.authorization.submitted',
    underReview: 'adrine.insurance.authorization.under_review',
    approved: 'adrine.insurance.authorization.approved',
    partiallyApproved: 'adrine.insurance.authorization.partially_approved',
    rejected: 'adrine.insurance.authorization.rejected',
    settled: 'adrine.insurance.authorization.settled',
    withdrawn: 'adrine.insurance.authorization.withdrawn',
  },
  discharge: {
    summaryDrafted: 'adrine.discharge.summary.drafted',
    initiated: 'adrine.discharge.orchestration.initiated',
    clinicalCleared: 'adrine.discharge.clinical.cleared',
    billingCleared: 'adrine.discharge.billing.cleared',
    pharmacyCleared: 'adrine.discharge.pharmacy.cleared',
    nursingCleared: 'adrine.discharge.nursing.cleared',
    insuranceCleared: 'adrine.discharge.insurance.cleared',
    completed: 'adrine.discharge.completed',
    cancelled: 'adrine.discharge.orchestration.cancelled',
  },
  workflow: {
    escalated: 'adrine.workflow.escalation.created',
    automationRan: 'adrine.workflow.automation.executed',
  },
  ai: {
    summaryGenerated: 'adrine.ai.summary.generated',
    alertRaised: 'adrine.ai.alert.raised',
  },
  governance: {
    configPublished: 'adrine.config.published',
    approvalRequired: 'adrine.approval.required',
    approvalGranted: 'adrine.approval.granted',
    policyPublished: 'adrine.governance.policy.published',
    policyOverrideApplied: 'adrine.governance.policy.override_applied',
    roleAssigned: 'adrine.governance.role.assigned',
  },
  command: {
    snapshotGenerated: 'adrine.command.snapshot.generated',
  },
  escalation: {
    created: 'adrine.escalation.created',
    acknowledged: 'adrine.escalation.acknowledged',
    resolved: 'adrine.escalation.resolved',
  },
  workflowConfig: {
    published: 'adrine.workflow_config.published',
    rolledBack: 'adrine.workflow_config.rolled_back',
  },
  provisioning: {
    signupCreated: 'adrine.provisioning.signup.created',
    onboardingStepCompleted: 'adrine.provisioning.onboarding.step_completed',
    tenantActivated: 'adrine.provisioning.tenant.activated',
  },
  platformBilling: {
    subscribed: 'adrine.platform_billing.subscribed',
    usageRecorded: 'adrine.platform_billing.usage.recorded',
    quotaExceeded: 'adrine.platform_billing.quota.exceeded',
    invoiceGenerated: 'adrine.platform_billing.invoice.generated',
  },
  modules: {
    enabled: 'adrine.modules.entitlement.enabled',
    disabled: 'adrine.modules.entitlement.disabled',
  },
  migration: {
    jobCreated: 'adrine.migration.job.created',
    jobExecuted: 'adrine.migration.job.executed',
    jobRolledBack: 'adrine.migration.job.rolled_back',
  },
  notifications: {
    enqueued: 'adrine.notifications.outbox.enqueued',
    delivered: 'adrine.notifications.delivery.completed',
    failed: 'adrine.notifications.delivery.failed',
  },
  integrations: {
    apiKeyCreated: 'adrine.integrations.api_key.created',
    webhookDelivered: 'adrine.integrations.webhook.delivered',
    webhookFailed: 'adrine.integrations.webhook.failed',
  },
  aiOrchestration: {
    actionExecuted: 'adrine.ai.action.executed',
    quotaExceeded: 'adrine.ai.quota.exceeded',
  },
  templates: {
    instantiated: 'adrine.templates.pack.instantiated',
  },
} as const;

/** Flatten nested event catalog (keyof on a union of categories was resolving to `never`). */
export type PlatformEventName = {
  [Category in keyof typeof HospitalPlatformEvents]: (typeof HospitalPlatformEvents)[Category][keyof (typeof HospitalPlatformEvents)[Category]];
}[keyof typeof HospitalPlatformEvents];
