import { HospitalPlatformEvents } from '../events.js';
import type { LifecycleDefinition } from '../types.js';

export type OpdVisitState =
  | 'intent'
  | 'registered'
  | 'appointment_or_walkin'
  | 'checked_in'
  | 'routed'
  | 'queued'
  | 'in_consultation'
  | 'orders_pending'
  | 'billing_pending'
  | 'follow_up_scheduled'
  | 'completed'
  | 'cancelled'
  | 'no_show';

export const opdVisitLifecycle: LifecycleDefinition<OpdVisitState> = {
  id: 'opd_visit',
  label: 'OPD visit',
  initial: 'intent',
  states: [
    'intent',
    'registered',
    'appointment_or_walkin',
    'checked_in',
    'routed',
    'queued',
    'in_consultation',
    'orders_pending',
    'billing_pending',
    'follow_up_scheduled',
    'completed',
    'cancelled',
    'no_show',
  ],
  transitions: [
    {
      from: 'intent',
      to: 'registered',
      action: 'register_patient',
      roles: ['receptionist', 'admin'],
      validations: ['demographics_complete', 'consent_captured'],
      emits: [HospitalPlatformEvents.patient.registered],
      notifications: ['patient_welcome_sms'],
      metering: ['opd.registration'],
      aiHooks: ['duplicate_patient_check'],
      branchConfigKeys: ['opd.require_abha', 'opd.require_consent'],
      auditLevel: 'phi',
    },
    {
      from: 'registered',
      to: 'appointment_or_walkin',
      action: 'schedule_or_walkin',
      roles: ['receptionist', 'scheduler'],
      validations: ['department_selected', 'doctor_or_pool_assigned'],
      emits: [HospitalPlatformEvents.appointment.booked],
      metering: ['opd.appointment_booked'],
      aiHooks: ['slot_optimization_hint'],
      branchConfigKeys: ['scheduling.walk_in_enabled'],
      auditLevel: 'standard',
    },
    {
      from: ['appointment_or_walkin', 'registered'],
      to: 'checked_in',
      action: 'check_in',
      roles: ['receptionist'],
      validations: ['appointment_exists_or_walkin_allowed', 'patient_balance_ok'],
      emits: [HospitalPlatformEvents.appointment.checkedIn],
      notifications: ['patient_checked_in_sms'],
      metering: ['opd.check_in'],
      reversibleBy: ['reverse_check_in'],
      auditLevel: 'standard',
    },
    {
      from: 'checked_in',
      to: 'appointment_or_walkin',
      action: 'reverse_check_in',
      roles: ['admin', 'receptionist'],
      validations: ['no_active_consultation'],
      emits: [HospitalPlatformEvents.workflow.automationRan],
      reversibleBy: [],
      auditLevel: 'standard',
    },
    {
      from: 'checked_in',
      to: 'routed',
      action: 'route_to_department',
      roles: ['receptionist', 'nurse'],
      validations: ['department_selected', 'doctor_or_pool_assigned'],
      emits: [HospitalPlatformEvents.encounter.opened],
      metering: ['opd.department_routed'],
      branchConfigKeys: ['opd.auto_route_by_specialty'],
      auditLevel: 'standard',
    },
    {
      from: ['checked_in', 'routed'],
      to: 'queued',
      action: 'issue_token',
      roles: ['receptionist'],
      validations: ['token_not_duplicate_today'],
      emits: [HospitalPlatformEvents.queue.tokenIssued],
      notifications: ['patient_token_sms'],
      metering: ['opd.token_issued'],
      auditLevel: 'standard',
    },
    {
      from: 'queued',
      to: 'in_consultation',
      action: 'call_patient',
      roles: ['receptionist', 'doctor', 'jr_doctor', 'nurse'],
      emits: [HospitalPlatformEvents.queue.called],
      notifications: ['doctor_patient_ready'],
      metering: ['opd.consultation_started'],
      blockedWhenEscalated: true,
      auditLevel: 'standard',
    },
    {
      from: 'in_consultation',
      to: 'in_consultation',
      action: 'record_vitals',
      roles: ['nurse', 'doctor', 'jr_doctor'],
      validations: ['vitals_within_range_or_escalated'],
      emits: [HospitalPlatformEvents.clinical.vitalsRecorded],
      metering: ['opd.vitals_recorded'],
      aiHooks: ['vitals_anomaly_alert'],
      auditLevel: 'phi',
    },
    {
      from: 'in_consultation',
      to: 'in_consultation',
      action: 'save_clinical_note',
      roles: ['doctor'],
      validations: ['clinical_note_present'],
      emits: [HospitalPlatformEvents.clinical.noteSigned],
      metering: ['opd.clinical_note'],
      aiHooks: ['scribe_assist', 'coding_suggestion'],
      auditLevel: 'phi',
    },
    {
      from: 'in_consultation',
      to: 'queued',
      action: 'release_for_senior_handoff',
      roles: ['doctor', 'jr_doctor', 'admin'],
      emits: [HospitalPlatformEvents.queue.tokenIssued],
      metering: ['opd.senior_handoff_released'],
      auditLevel: 'standard',
    },
    {
      from: 'in_consultation',
      to: 'orders_pending',
      action: 'complete_consultation',
      roles: ['doctor'],
      validations: ['clinical_note_present', 'diagnosis_coded'],
      emits: [HospitalPlatformEvents.encounter.closed],
      notifications: ['nurse_orders_pending'],
      metering: ['opd.consultation_completed'],
      aiHooks: ['order_set_suggestion'],
      auditLevel: 'phi',
    },
    {
      from: 'orders_pending',
      to: 'orders_pending',
      action: 'place_orders',
      roles: ['doctor'],
      validations: ['encounter_open'],
      emits: [
        HospitalPlatformEvents.lab.ordered,
        HospitalPlatformEvents.radiology.ordered,
        HospitalPlatformEvents.clinical.prescriptionIssued,
      ],
      metering: ['opd.orders_placed'],
      auditLevel: 'phi',
    },
    {
      from: 'orders_pending',
      to: 'billing_pending',
      action: 'fulfill_or_defer_orders',
      roles: ['doctor', 'nurse', 'lab_technician', 'pharmacist', 'radiologist', 'receptionist'],
      validations: [
        'critical_results_acknowledged',
        'pending_orders_deferred_or_complete',
        'pending_mandatory_labs_complete',
        'critical_labs_acknowledged',
        'pending_pharmacy_fulfilled_or_deferred',
        'controlled_meds_approved',
      ],
      emits: [HospitalPlatformEvents.workflow.automationRan],
      metering: ['opd.orders_cleared'],
      auditLevel: 'standard',
    },
    {
      from: 'billing_pending',
      to: 'billing_pending',
      action: 'generate_invoice',
      roles: ['receptionist', 'billing'],
      validations: ['encounter_closed', 'invoice_exists'],
      emits: [HospitalPlatformEvents.billing.invoiceGenerated],
      metering: ['opd.invoice_generated'],
      auditLevel: 'standard',
    },
    {
      from: 'billing_pending',
      to: 'billing_pending',
      action: 'collect_payment',
      roles: ['receptionist', 'billing'],
      validations: ['invoice_exists'],
      emits: [HospitalPlatformEvents.billing.paymentReceived],
      notifications: ['payment_receipt_sms'],
      metering: ['opd.payment_collected'],
      branchConfigKeys: ['billing.allow_partial_payment'],
      auditLevel: 'standard',
    },
    {
      from: 'billing_pending',
      to: 'completed',
      action: 'settle_bill',
      roles: ['receptionist', 'billing'],
      validations: ['invoice_settled_or_credit_approved'],
      emits: [
        HospitalPlatformEvents.billing.invoiceSettled,
        HospitalPlatformEvents.opd.visitCompleted,
        HospitalPlatformEvents.queue.completed,
      ],
      notifications: ['visit_summary_sms'],
      metering: ['opd.visit_completed'],
      auditLevel: 'standard',
    },
    {
      from: 'completed',
      to: 'follow_up_scheduled',
      action: 'schedule_follow_up',
      roles: ['doctor', 'receptionist', 'scheduler'],
      validations: ['follow_up_date_valid'],
      emits: [HospitalPlatformEvents.appointment.booked],
      metering: ['opd.follow_up_scheduled'],
      auditLevel: 'standard',
    },
    {
      from: 'follow_up_scheduled',
      to: 'completed',
      action: 'close_follow_up_task',
      roles: ['receptionist', 'scheduler'],
      auditLevel: 'standard',
    },
    {
      from: [
        'registered',
        'appointment_or_walkin',
        'checked_in',
        'routed',
        'queued',
        'in_consultation',
        'orders_pending',
        'billing_pending',
      ],
      to: 'billing_pending',
      action: 'escalate_visit',
      roles: ['receptionist', 'doctor', 'nurse', 'admin'],
      validations: ['escalation_reason_provided'],
      emits: [HospitalPlatformEvents.workflow.escalated],
      notifications: ['supervisor_escalation_alert'],
      metering: ['opd.escalation'],
      auditLevel: 'critical',
    },
    {
      from: ['appointment_or_walkin', 'checked_in', 'queued', 'routed'],
      to: 'no_show',
      action: 'mark_no_show',
      roles: ['receptionist', 'admin'],
      emits: [HospitalPlatformEvents.appointment.noShow],
      metering: ['opd.no_show'],
      auditLevel: 'standard',
    },
    {
      from: [
        'intent',
        'registered',
        'appointment_or_walkin',
        'checked_in',
        'routed',
        'queued',
        'billing_pending',
      ],
      to: 'cancelled',
      action: 'cancel_visit',
      roles: ['receptionist', 'admin'],
      validations: ['cancel_reason_provided'],
      emits: [HospitalPlatformEvents.appointment.cancelled],
      metering: ['opd.cancelled'],
      auditLevel: 'standard',
    },
  ],
};
